language: java
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
deploy:
  provider: heroku
  api_key:
    secure: ZJN/f7JLBBPIBuMr9Ep/yj/HUS2W2GCs3RHPKIjuKUNBU88X2aEC3gfbX3ywHxTgpZHDsptjaBLfLQgLEKGEc2wwKDgQzTVL38tlkzhkkzsnl9VsuVWGPpHdEmaYloq/tdIIRJXAD5MCv1Wp1o7NTSCM9g1VR8lpEu08GxAWnKRnzZh7/QBpwTzk/UUpCzXQbg8oupB8HSz6JKo9zbo2pvWDTBlzc7OZnOi5vtlC+ThXcJcTl0zSxeyrHKjerxpJuSb9EcyKgtw4wDfJZDEqA9Kcnh+MziEb5i5tbnjHHZMg1zuX9kMGkte41VHDgQwOa74d+p8ahFTKJdsF3p+qlw63iMIsemJ2/3ULdIecBmDMQfh40BCq+3Lauh/9xnNfWXJ7bELtwAYgTZhyHj0hXCY45jKx363M+rbODdxVnDqzVkVyEi1clAzAGY9S9VEMOHQtwSVD4SPprSzOW+t+p94jRSfTYa6k7xWexftnQmY9qB5Umy49Wxu7U2wya92NaGwFgOaeZ0O1Is9cYkK2tyUF6nJfB2yMvYl/zY9qFg/yvZK5zFu1lB3iFwvUdbPcC4gSBLyZhldxj8sNByVENQ2CSYzckUB2uTWs4ieRbi2aNh+ZqT0K8HKCASPOe9eSH9acoolQ5cI6N7V4Mp7aDx2ZAHVu/T0MnssNwda/ghw=
  app: tigerffff
